version: '3'
services:

  app:
    build:
        context: ./src
        dockerfile: Dockerfile.App
    restart: always
    networks:
      - demo_network
    ports:
      - '5000:5000'

  web-server:
    build:
        context: ./src
        dockerfile: Dockerfile.Web
    restart: always
    networks:
      - demo_network
    ports:
      - '80:80'

networks:
  demo_network:
    driver: bridge